name: Pourcast Trigger

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  pourcast_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Run Bourbon Pourcast Script
        run: python wakeabc_search.py

      - name: Debug: Check GH_PAT
        run: |
          if [ -z "${{ secrets.GH_PAT }}" ]; then
            echo "❌ GH_PAT is EMPTY"
            exit 1
          else
            echo "✅ GH_PAT is set"
          fi

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-update: bourbon results" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
