name: Run Bourbon Pourcast

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 UTC

jobs:
  run-pourcast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Run Bourbon Pourcast Script
        run: python wakeabc_search.py

      - name: Send Email with Results
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
        run: python send_email.py

      - name: Commit and Push Results
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add bourbon_report.pdf search_results.html search_results.txt
          git commit -m "Auto-update: bourbon results" || echo "Nothing to commit"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
