name: Run WakeABC Search and Send Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12,22 * * *"  # Runs at 12 PM and 10 PM UTC (adjust for your timezone)

jobs:
  search-and-email:
    runs-on: ubuntu-latest

    env:
      MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
      RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run search and generate PDF
        run: python wakeabc_search.py

      - name: Send email with PDF report
        run: python send_mailgun_email.py