name: WakeABC Bourbon Search

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12,22 * * *'  # Runs at 12:00 PM and 10:00 PM UTC daily

jobs:
  run-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run wakeabc_search.py
        run: python wakeabc_search.py
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
          MAILGUN_RECIPIENT: ${{ secrets.MAILGUN_RECIPIENT }}
          MAILGUN_SENDER: ${{ secrets.MAILGUN_SENDER }}

      - name: Commit & push bourbon_report.pdf
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add bourbon_report.pdf
          git commit -m "Auto-update bourbon_report.pdf [skip ci]" || echo "No changes to commit"
          git push
